data_source ifs_table:
  type: bigquery
  connection:
    account_info_json_path: include/gcp/service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: "project-stats-fin"
    dataset: ifs
soda_cloud:
  host: cloud.soda.io
  api_key_id: fb5e48b3-4c68-4b14-8b3f-98d1b0744596
  api_key_secret: JoxRWdqpPG6nktlMIJ2Gk7iuDMqalQoDwQswu9wiDdhjRHKK0qCr7A