data_source your_data_source_name:
  type: bigquery
  connection:
    account_info_json_path: include/gcp/service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: your_project_id
    dataset: your_dataset_name
soda_cloud:
  host: cloud.soda.io
  api_key_id: soda_api_key_id
  api_key_secret: soda_key_secret